// 성분 영문 코드 → 한국어 이름 (tools/hff/substance.csv 에서 생성 — 손으로 고치지 말 것)
// 용도: 서버 판정(quick_check_v1)의 DUR 결과가 영문 성분 코드로 오므로 화면 표시에 쓴다.
export const SUBSTANCE_NAMES: Record<string, string> = {
  "ezetimibe": "에제티미브",
  "metformin": "메트포르민",
  "alendronate": "알렌드로네이트",
  "vitamin_d": "비타민 D",
  "calcium": "칼슘",
  "vitamin_b12": "비타민 B12",
  "magnesium": "마그네슘",
  "coenzyme_q10": "코엔자임 Q10",
  "statin": "스타틴",
  "melatonin": "멜라토닌",
  "folate": "엽산",
  "omega3": "오메가-3",
  "caffeine": "카페인",
  "beta_carotene": "베타카로틴",
  "vitamin_a": "비타민 A",
  "garcinia_cambogia": "가르시니아",
  "green_tea_extract": "녹차 카테킨",
  "cissus": "시서스",
  "banaba_leaf": "바나바잎",
  "bitter_melon": "여주",
  "resistant_maltodextrin": "난소화성 말토덱스트린",
  "antidiabetic_drug": "혈당강하제",
  "red_yeast_rice": "홍국",
  "phytosterol": "식물스테롤",
  "nattokinase": "나토키나제",
  "ginkgo_biloba": "은행잎",
  "beta_glucan": "베타글루칸",
  "zinc": "아연",
  "vitamin_c": "비타민 C",
  "probiotics": "프로바이오틱스",
  "vitamin_e": "비타민 E",
  "polyphenol": "폴리페놀",
  "curcumin": "커큐민",
  "resveratrol": "레스베라트롤",
  "prebiotics": "프리바이오틱스",
  "ginger": "생강",
  "honeysuckle": "인동덩굴",
  "milk_thistle": "밀크씨슬",
  "n_acetylcysteine": "NAC",
  "hovenia_dulcis": "헛개나무",
  "phosphatidylserine": "포스파티딜세린",
  "rhodiola": "홍경천",
  "ashwagandha": "아슈와간다",
  "l_theanine": "테아닌",
  "vitamin_k2": "비타민 K2",
  "glucosamine": "글루코사민",
  "msm": "MSM",
  "boswellia": "보스웰리아",
  "leucine": "류신",
  "hmb": "HMB",
  "bisphosphonate": "비스포스포네이트",
  "isoflavone": "이소플라본",
  "gamma_linolenic_acid": "감마리놀렌산",
  "saw_palmetto": "쏘팔메토",
  "collagen": "콜라겐",
  "lutein": "루테인",
  "tamoxifen": "타목시펜",
  "anticoagulant": "항응고제",
  "antiplatelet": "항혈소판제",
  "immunosuppressant": "면역억제제",
  "korean_red_ginseng": "홍삼",
  "vitamin_b_complex": "비타민 B군",
  "beta_blocker": "베타차단제",
  "diuretic": "이뇨제",
  "antihypertensive": "혈압약",
  "zeaxanthin": "지아잔틴",
  "hypnotic": "수면제",
  "antidepressant": "항우울제",
  "warfarin": "와파린",
  "hyaluronic_acid": "히알루론산",
  "astaxanthin": "아스타잔틴",
  "black_cohosh": "블랙코호시",
  "sulfonylurea": "설폰요소제",
  "insulin": "인슐린",
  "copper": "구리",
  "lovastatin": "로바스타틴",
  "atorvastatin": "아토르바스타틴",
  "glimepiride": "글리메피리드",
  "amoxicillin": "아목시실린",
  "saccharomyces_boulardii": "사카로마이세스 보울라디",
  "lactobacillus_rhamnosus_gg": "락토바실러스 람노서스 GG",
  "antibiotic": "항생제",
  "antithrombotic": "항혈전제",
  "ginseng": "인삼",
  "aspirin": "아스피린",
  "ppi": "PPI",
  "h2_blocker": "H2차단제",
  "bismuth": "비스무트",
  "protein": "단백질",
  "nmn": "NMN",
  "spermidine": "스퍼미딘",
  "st_johns_wort": "세인트존스워트",
  "iron": "철분",
  "iodine": "요오드",
  "amlodipine": "암로디핀",
  "ssri": "SSRI",
  "snri": "SNRI",
  "digoxin": "디곡신",
  "anticancer_drug": "항암제",
  "nifedipine": "니페디핀",
  "calcium_channel_blocker": "칼슘통로차단제",
  "grapefruit": "자몽",
  "vitamin_k": "비타민 K",
  "garlic": "마늘",
  "cranberry": "크랜베리",
  "undenatured_type_2_collagen": "비변성 II형 콜라겐",
  "losartan": "로사르탄",
  "arb": "ARB",
  "psyllium": "차전자피",
  "potassium": "칼륨",
  "furosemide": "푸로세미드",
  "loop_diuretic": "루프이뇨제",
  "thiamine": "티아민",
  "licorice": "감초",
  "clopidogrel": "클로피도그렐",
  "amiodarone": "아미오다론",
  "kelp": "켈프",
  "hydrochlorothiazide": "히드로클로로티아지드",
  "thiazide_diuretic": "티아지드 이뇨제",
  "tart_cherry": "타트체리 추출물",
  "niacin": "나이아신",
  "apixaban": "아픽사반",
  "doac": "DOAC",
  "policosanol": "폴리코사놀",
  "semaglutide": "세마글루타이드",
  "glp1_agonist": "GLP-1 수용체작용제",
  "chromium": "크롬",
  "levothyroxine": "레보티록신",
  "biotin": "비오틴",
  "sglt2_inhibitor": "SGLT2 억제제",
  "dapagliflozin": "다파글리플로진",
  "febuxostat": "페북소스타트",
  "dpp4_inhibitor": "DPP-4 억제제",
  "alpha_lipoic_acid": "알파리포산",
  "methimazole": "메티마졸",
  "prednisolone": "프레드니솔론",
  "glucocorticoid": "글루코코르티코이드",
  "inositol": "이노시톨",
  "esa": "적혈구조혈자극제",
  "erythropoietin": "에리트로포이에틴",
  "darbepoetin": "다베포에틴",
  "carnitine": "카르니틴",
  "starfruit": "스타프루트",
  "phosphorus": "인",
  "tacrolimus": "타크로리무스",
  "mycophenolate_mofetil": "미코페놀레이트 모페틸",
  "echinacea": "에키네시아",
  "vitamin_b6": "비타민 B6",
  "tamsulosin": "탐스로신",
  "alpha_blocker": "α차단제",
  "pumpkin_seed_extract": "호박씨 추출물",
  "antimuscarinic": "항무스카린제",
  "potassium_citrate": "구연산칼륨",
  "tolvaptan": "톨밥탄",
  "levodopa": "레보도파",
  "carbidopa": "카르비도파",
  "kava": "카바",
  "escitalopram": "에스시탈로프람",
  "five_htp": "5-HTP",
  "tryptophan": "트립토판",
  "benzodiazepine": "벤조디아제핀",
  "valerian": "발레리안",
  "topiramate": "토피라메이트",
  "propranolol": "프로프라놀롤",
  "vitamin_b2": "비타민 B2",
  "valproic_acid": "발프로산",
  "carbamazepine": "카르바마제핀",
  "anticonvulsant": "항경련제",
  "donepezil": "도네페질",
  "cholinesterase_inhibitor": "콜린에스터라제 억제제",
  "anticholinergic": "항콜린성 약물",
  "interferon": "인터페론",
  "s1p_modulator": "S1P조절제",
  "immunomodulator": "면역조절제",
  "duloxetine": "둘록세틴",
  "methylphenidate": "메틸페니데이트",
  "citrus_aurantium": "시트러스 아우란티움",
  "glycine": "글리신",
  "pregabalin": "프레가발린",
  "methotrexate": "메토트렉세이트",
  "allopurinol": "알로푸리놀",
  "nsaid": "NSAID",
  "orlistat": "오를리스타트",
  "chondroitin": "콘드로이틴",
  "peppermint_oil": "페퍼민트오일",
  "inulin": "이눌린",
  "biologics": "생물학적제제",
  "tenofovir": "테노포비르",
  "entecavir": "엔테카비르",
  "antiviral": "항바이러스제",
  "lactulose": "락툴로오스",
  "bcaa": "분지사슬아미노산",
  "manganese": "망간",
  "pancreatic_enzyme": "췌장효소",
  "inhaled_corticosteroid": "흡입 스테로이드",
  "laba": "지속성 베타작용제",
  "bronchodilator": "기관지확장제",
  "quercetin": "케르세틴",
  "pirfenidone": "피르페니돈",
  "antifibrotic": "항섬유화제",
  "isoniazid": "이소니아지드",
  "antituberculosis_drug": "항결핵제",
  "propolis": "프로폴리스",
  "anti_obesity_drug": "항비만약",
  "phentermine": "펜터민",
  "naltrexone": "날트렉손",
  "bupropion": "부프로피온",
  "liraglutide": "리라글루타이드",
  "multivitamin": "종합비타민",
  "finasteride": "피나스테리드",
  "antioxidant": "고용량 항산화제",
  "antiretroviral": "항레트로바이러스제",
  "protease_inhibitor": "프로테아제억제제",
  "nnrti": "비뉴클레오시드 역전사효소억제제",
  "integrase_inhibitor": "인테그라제억제제",
  "polyvalent_cation": "다가양이온",
  "ras_blocker": "RAS차단제",
  "potassium_sparing_diuretic": "칼륨보존이뇨제",
  "soy": "콩",
  "gaba": "감마-아미노부티르산",
  "gamma_oryzanol": "감마오리자놀",
  "creatine": "크레아틴",
  "l_arginine": "L-아르기닌",
  "cynanchum_wilfordii_complex": "백수오등복합추출물",
  "sophora_japonica_fruit_extract": "회화나무열매추출물",
  "milk_protein_hydrolysate": "유단백가수분해물",
  "lactobacillus": "락토바실러스",
  "lithium": "리튬",
  "rivaroxaban": "리바록사반",
  "cyclosporine": "사이클로스포린",
  "heparin": "헤파린",
  "phenytoin": "페니토인",
  "comfrey": "컴프리",
  "piperine": "피페린",
  "green_tea_extract_egcg": "녹차 추출물(EGCG)",
  "cimicifuga": "승마",
  "aloe_anthraquinone": "알로에(안트라퀴논)",
  "cod_liver_oil": "코드간유·상어연골",
  "oral_contraceptive": "경구 피임약",
};

export function substanceName(code: string): string {
  return SUBSTANCE_NAMES[code] ?? code;
}
