-- 성분 사전 확장 (2026-10-03): 식약처 DUR 성분 487개 중 한글명이 확보된 것을 substance 에 추가
-- 한글명 출처: DUR 제품명의 괄호 성분명(단일 성분 제품, 염 꼬리 제거) + 손으로 보탠 표. 심평원 일반명은 영문이라 쓰지 않음.
-- 안전장치: code 또는 같은 name_ko 가 이미 있으면 건너뜀. kind 는 기존 'aspirin' 행 값을 복사. aliases 에 염 포함 원문.
-- 실행 순서: 이 파일 → migrate-quick-check-rpc.sql(v3.1, aliases 매칭) → migrate-atc-class-members.sql(새 성분의 계열)
drop table if exists _new_subst;
create temp table _new_subst (code text, name_ko text, aliases text[], src text);
insert into _new_subst (code, name_ko, aliases, src) values
  ('5-fluorouracil', '플루오로우라실', '{}'::text[], 'auto'),
  ('abacavir', '아바카비르', '{}'::text[], 'manual'),
  ('aceclofenac', '아세클로페낙', '{}'::text[], 'auto'),
  ('acetaminophen', '아세트아미노펜', '{}'::text[], 'manual'),
  ('acetazolamide', '아세타졸아미드', '{}'::text[], 'auto'),
  ('acitretin', '아시트레틴', '{}'::text[], 'auto/review'),
  ('adefovir dipivoxil', '아데포비어', array['아데포비어디피복실']::text[], 'auto'),
  ('agalsidase α', '아갈시다제알파', '{}'::text[], 'auto/review'),
  ('agomelatine', '아고멜라틴', '{}'::text[], 'auto/review'),
  ('alfacalcidol', '알파칼시돌', '{}'::text[], 'auto'),
  ('alfentanil', '알펜타닐', '{}'::text[], 'manual'),
  ('alfuzosin', '알푸조신', array['알푸조신염산염']::text[], 'auto'),
  ('alitretinoin', '알리트레티노인', '{}'::text[], 'auto'),
  ('almotriptan', '알모트립탄', array['알모트립탄말산염']::text[], 'auto/review'),
  ('alogliptin', '알로글립틴', '{}'::text[], 'manual'),
  ('alprazolam', '알프라졸람', '{}'::text[], 'auto'),
  ('amantadine', '아만타딘', array['아만타딘황산염']::text[], 'auto'),
  ('amiloride', '염산아미로라이드', '{}'::text[], 'auto/review'),
  ('amiodarone', '아미오다론', array['아미오다론염산염']::text[], 'auto'),
  ('amisulpride', '아미설프리드', array['아미설피리드']::text[], 'auto'),
  ('amitriptyline', '아미트리프틸린', array['아미트리프틸린염산염']::text[], 'auto'),
  ('amlodipine', '암로디핀', '{}'::text[], 'manual'),
  ('amlodipine camsylate', '암로디핀캄실산염', '{}'::text[], 'manual'),
  ('anagliptin', '아나글립틴', '{}'::text[], 'manual'),
  ('anagrelide', '아나그렐리드', array['아나그렐리드염산염']::text[], 'auto'),
  ('anastrozole', '아나스트로졸', '{}'::text[], 'auto'),
  ('apalutamide', '아팔루타마이드', '{}'::text[], 'auto/review'),
  ('apixaban', '아픽사반', '{}'::text[], 'auto'),
  ('apraclonidine', '아프라클로니딘', array['아프라클로니딘염산염']::text[], 'auto/review'),
  ('arsenic trioxide', '삼산화비소', array['바이알']::text[], 'auto'),
  ('ascorbic acid', '아스코르브산', '{}'::text[], 'manual'),
  ('aspirin', '아스피린', array['아스피린장용과립']::text[], 'auto'),
  ('atazanavir', '아타자나비르', '{}'::text[], 'manual'),
  ('atomoxetine', '아토목세틴', array['아토목세틴염산염']::text[], 'auto'),
  ('atorvastatin', '아토르바스타틴', array['무수아토르바스타틴칼슘','아토르바스타틴칼슘','아토르바스타틴칼슘삼수화물','아토르바스타틴칼슘수화물']::text[], 'auto'),
  ('atorvastatin strontium pentahydrate', '아토르바스타틴스트론튬오', array['아토르바스타틴스트론튬오수화물']::text[], 'auto'),
  ('atropine', '아트로핀', '{}'::text[], 'manual'),
  ('azathioprine', '아자티오프린', '{}'::text[], 'auto'),
  ('azithromycin', '아지트로마이신', array['아지트로마이신수화물']::text[], 'auto'),
  ('bedaquiline', '베다퀼린', array['베다퀼린푸마르산염']::text[], 'auto/review'),
  ('benfotiamine', '벤포티아민', '{}'::text[], 'manual'),
  ('benserazide', '벤세라지드', '{}'::text[], 'manual'),
  ('bicalutamide', '비칼루타미드', array['비칼루타마이드']::text[], 'auto'),
  ('bictegravir', '빅테그라비르', '{}'::text[], 'manual'),
  ('blonanserin', '블로난세린', '{}'::text[], 'auto'),
  ('bosentan', '보센탄', array['보센탄수화물']::text[], 'auto/review'),
  ('bosutinib', '보수티닙', array['보수티닙일수화물']::text[], 'auto'),
  ('brigatinib', '브리가티닙', '{}'::text[], 'auto'),
  ('brimonidine', '브리모니딘', array['브리모니딘타르타르산염']::text[], 'auto'),
  ('bromhexine', '브롬헥신', '{}'::text[], 'manual'),
  ('bromocryptine', '브로모크립틴', array['브로모크립틴메실산염']::text[], 'auto/review'),
  ('brompheniramine', '브롬페니라민', '{}'::text[], 'manual'),
  ('buprenorphine', '부프레노르핀', '{}'::text[], 'auto'),
  ('bupropion', '부프로피온', array['부프로피온염산염']::text[], 'auto'),
  ('burosumab', '부로수맙', '{}'::text[], 'manual'),
  ('buspirone', '부스피론', array['부스피론염산염']::text[], 'auto'),
  ('cabotegravir', '카보테그라비르', '{}'::text[], 'auto/review'),
  ('cabotegravir sodium micronized', '카보테그라비르', array['카보테그라비르나트륨']::text[], 'auto/review'),
  ('cabozantinib s-malate', '카보잔티닙', '{}'::text[], 'auto'),
  ('caffeine', '카페인', '{}'::text[], 'manual'),
  ('calcitriol', '칼시트리올', '{}'::text[], 'auto'),
  ('calcium', '글루콘산', array['글루콘산칼슘수화물','염화칼슘수화물']::text[], 'auto'),
  ('candesartan cilexetil', '칸데사르탄', '{}'::text[], 'manual'),
  ('capecitabine', '카페시타빈', '{}'::text[], 'auto'),
  ('carbamazepine', '카르바마제핀', '{}'::text[], 'auto'),
  ('carbidopa', '카르비도파', '{}'::text[], 'manual'),
  ('carbinoxamine', '카르비녹사민', '{}'::text[], 'manual'),
  ('celecoxib', '세레콕시브', '{}'::text[], 'auto'),
  ('ceritinib', '세리티닙', '{}'::text[], 'auto/review'),
  ('chlorpheniramine', '클로르페니라민', '{}'::text[], 'manual'),
  ('chlorpromazine', '클로르프로마진', array['클로르프로마진염산염']::text[], 'auto/review'),
  ('chlorthalidone', '클로르탈리돈', '{}'::text[], 'auto'),
  ('choline fenofibrate', '콜린페노피브레이트', '{}'::text[], 'manual'),
  ('cilastatin', '실라스타틴', '{}'::text[], 'manual'),
  ('ciprofloxacin', '시프로플록사신', array['시프로플록사신염산염','시프로플록사신염산염수화물','염산시프로플록사신']::text[], 'auto'),
  ('clarithromycin', '클래리트로마이신', array['클래리스로마이신','클래리트로마이신제피과립']::text[], 'auto'),
  ('clomipramine', '클로미프라민', array['클로미프라민염산염']::text[], 'auto'),
  ('clonidine', '클로니딘', array['클로니딘염산염']::text[], 'auto/review'),
  ('clonixin lysinate', '클로닉신리시네이트', '{}'::text[], 'auto'),
  ('clopidogrel', '클로피도그렐', array['클로피도그렐베실산염']::text[], 'auto/review'),
  ('clopidogrel bisulfate', '클로피도그렐', array['클로피도그렐황산수소염','클로피도그렐황산염','황산수소클로피도그렐']::text[], 'auto'),
  ('clopidogrel camsylate', '클로피도그렐', array['클로피도그렐캄실산염']::text[], 'auto/review'),
  ('clopidogrel napadisilate', '클로피도그렐나파디실레이트', array['클로피도그렐나파디실레이트일수화물']::text[], 'auto/review'),
  ('clopidogrel resinate', '클로피도그렐레지네이트', '{}'::text[], 'auto/review'),
  ('cobicistat', '코비시스타트', '{}'::text[], 'manual'),
  ('colchicine', '콜키신', '{}'::text[], 'auto'),
  ('cyanocobalamin', '시아노코발라민', '{}'::text[], 'manual'),
  ('cyclobenzaprine', '시클로벤자프린', array['시클로벤자프린염산염']::text[], 'auto'),
  ('cyclosporine', '사이클로스포린', '{}'::text[], 'auto'),
  ('cyproheptadine orotate', '시프로헵타딘', '{}'::text[], 'manual'),
  ('d-chlorpheniramine', '클로르페니라민', '{}'::text[], 'manual'),
  ('d-penicillamine', '디-페니실라민', '{}'::text[], 'auto'),
  ('dabigatran etexilate', '다비가트란에텍실레이트', array['다비가트란에텍실레이트메실산염']::text[], 'auto'),
  ('dapagliflozin', '다파글리플로진', '{}'::text[], 'manual'),
  ('dapoxetine', '다폭세틴', array['다폭세틴염산염']::text[], 'auto'),
  ('darunavir ethanolate', '다루나비르에탄올레이트', '{}'::text[], 'auto'),
  ('defibrotide', '데피브로타이드', '{}'::text[], 'auto/review'),
  ('degarelix', '데가렐릭스', '{}'::text[], 'auto'),
  ('delamanid', '델라마니드', '{}'::text[], 'auto/review'),
  ('desogestrel', '데소게스트렐', '{}'::text[], 'manual'),
  ('desvenlafaxine', '데스벤라팍신벤조산염', array['데스벤라팍신','데스벤라팍신숙신산염일수화물']::text[], 'auto'),
  ('deutetrabenazine', '듀테트라베나진', '{}'::text[], 'auto'),
  ('dexbrompheniramine', '덱스브롬페니라민', '{}'::text[], 'manual'),
  ('dexibuprofen', '덱시부프로펜', array['덱시부프로펜 디.씨','덱시부프로펜 디.씨.','덱시부프로펜디.씨','덱시부프로펜디.씨.']::text[], 'auto'),
  ('dexibuprofen d c', '덱시부프로펜디.씨', '{}'::text[], 'auto/review'),
  ('dexketoprofen trometamol', '덱스케토프로펜', array['덱스케토프로펜트로메타몰']::text[], 'auto+manual'),
  ('dexlansoprazole', '덱스란소프라졸', '{}'::text[], 'auto'),
  ('dextromethorphan', '덱스트로메토르판', '{}'::text[], 'manual'),
  ('diclofenac', '디클로페낙', array['디클로페낙나트륨']::text[], 'auto'),
  ('diclofenac-β-dimethyl-aminoethanol', '디클로페낙β-디메틸아미노에탄올', array['디클로페낙β-디메칠아미노에탄올','디클로페낙베타-디메틸아미노에탄올','디클로페낙베타디메칠아미노에탄올','디클로페낙베타디메틸아미노에탄올']::text[], 'auto'),
  ('diethylpropion', '디에틸프로피온', array['디에틸프로피온염산염']::text[], 'auto'),
  ('digoxin', '디곡신', '{}'::text[], 'auto'),
  ('diltiazem', '딜티아젬', array['딜티아젬아시딕폴리머콤플렉스','딜티아젬염산염']::text[], 'auto'),
  ('diluted nitroglycerin', '희석된니트로글리세린', array['니트로글리세린','희석니트로글리세린']::text[], 'auto'),
  ('diluted nitroglycerin solution', '니트로글리세린', array['희석한니트로글리세린용액']::text[], 'auto+manual'),
  ('diphenhydramine', '디펜히드라민', '{}'::text[], 'manual'),
  ('diphenylhydantoin', '페니토인', '{}'::text[], 'auto/review'),
  ('diprophylline', '디프로필린', '{}'::text[], 'manual'),
  ('divalproex', '디발프로엑스', array['디발프로엑스나트륨']::text[], 'auto'),
  ('divalproex sodium particle', '디발프로엑스나트륨입자', '{}'::text[], 'auto/review'),
  ('dl-carnitine', '카르니틴', '{}'::text[], 'manual'),
  ('dl-methylephedrine', '메틸에페드린', '{}'::text[], 'manual'),
  ('dl-methylephedrine hci', '메틸에페드린', '{}'::text[], 'manual'),
  ('dolutegravir', '돌루테그라비르', array['돌루테그라비르나트륨']::text[], 'auto/review'),
  ('domperidone', '돔페리돈', array['돔페리돈말레산염']::text[], 'auto'),
  ('doravirine', '도라비린', '{}'::text[], 'auto/review'),
  ('doripenem', '도리페넴', '{}'::text[], 'auto/review'),
  ('doxepin', '독세핀', array['독세핀염산염']::text[], 'auto'),
  ('doxycycline', '독시사이클린', array['독시사이클린수화물']::text[], 'auto'),
  ('doxycycline hyclate', '독시사이클린하이클레이트', array['독시사이클린하이클레이트수화물']::text[], 'auto/review'),
  ('doxylamine', '독실아민', '{}'::text[], 'manual'),
  ('dronedarone', '드로네다론', array['드로네다론염산염']::text[], 'auto'),
  ('drospirenone', '드로스피레논', '{}'::text[], 'manual'),
  ('duloxetine', '둘록세틴', array['둘록세틴염산염']::text[], 'auto'),
  ('ebastine', '에바스틴', '{}'::text[], 'auto'),
  ('edetate', '에데트산칼슘디', array['에데트산칼슘디나트륨']::text[], 'auto'),
  ('edoxaban', '에독사반', array['에독사반베실산염수화물','에독사반토실산염수화물']::text[], 'auto'),
  ('eliglustat', '엘리글루스타트', '{}'::text[], 'auto/review'),
  ('elvitegravir', '엘비테그라비르', '{}'::text[], 'manual'),
  ('empagliflozin', '엠파글리플로진', '{}'::text[], 'manual'),
  ('emtricitabine', '엠트리시타빈', '{}'::text[], 'manual'),
  ('enavogliflozin', '엔아보글리플로진', '{}'::text[], 'manual'),
  ('entacapone', '엔타카폰', '{}'::text[], 'manual'),
  ('entrectinib', '엔트렉티닙', '{}'::text[], 'auto'),
  ('enzalutamide', '엔잘루타마이드', array['엔잘루타미드']::text[], 'auto'),
  ('ephedrine', '에페드린', array['에페드린염산염']::text[], 'auto/review'),
  ('epinephrine', '에피네프린', array['에피네프린타르타르산염']::text[], 'auto'),
  ('ergotamine', '에르고타민', '{}'::text[], 'manual'),
  ('escitalopram', '에스시탈로프람', array['에스시탈로프람옥살산염']::text[], 'auto'),
  ('esomeprazole', '에스오메프라졸', array['에스오메프라졸나트륨','에스오메프라졸마그네슘','에스오메프라졸마그네슘삼수화물','에스오메프라졸마그네슘이수화물']::text[], 'auto'),
  ('esomeprazole strontium tetrahydrate', '에스오메프라졸스트론튬사', array['에스오메프라졸스트론튬사수화물']::text[], 'auto'),
  ('estrogen', '결합형에스트로겐', '{}'::text[], 'auto'),
  ('ethambutol', '에탐부톨', '{}'::text[], 'manual'),
  ('ethenzamide', '에텐자미드', '{}'::text[], 'manual'),
  ('ethinyl estradiol', '에티닐에스트라디올', '{}'::text[], 'manual'),
  ('ethyl esters of the iodised fatty acids of poppyseed oil', '아이오다이즈드오일', '{}'::text[], 'auto'),
  ('etodolac', '미분화에토돌락', array['에토돌락']::text[], 'auto'),
  ('etoricoxib', '에토리콕시브', '{}'::text[], 'auto'),
  ('etravirine', '에트라비린', '{}'::text[], 'auto/review'),
  ('everolimus', '에베로리무스', '{}'::text[], 'auto'),
  ('evogliptin', '에보글립틴', '{}'::text[], 'manual'),
  ('ezetimibe', '에제티미브', '{}'::text[], 'manual'),
  ('febuxostat', '페북소스타트', '{}'::text[], 'auto'),
  ('fedratinib dihydrochloride', '페드라티닙', array['페드라티닙염산염수화물']::text[], 'auto/review'),
  ('felodipine', '펠로디핀', '{}'::text[], 'auto'),
  ('fenofibrate', '페노피브레이트', '{}'::text[], 'manual'),
  ('fenofibric acid', '페노피브릭산', '{}'::text[], 'manual'),
  ('fenoterol', '페노테롤', array['페노테롤브롬화수소산염']::text[], 'auto/review'),
  ('fentanyl', '펜타닐', array['구연산펜타닐','바이알','펜타닐시트르산염']::text[], 'auto'),
  ('fexuprazan', '펙수프라잔', array['펙수프라잔염산염']::text[], 'auto'),
  ('filgotinib', '필고티닙', array['필고티닙말레산염']::text[], 'auto'),
  ('fimasartan', '피마사르탄', '{}'::text[], 'manual'),
  ('finerenone', '피네레논', '{}'::text[], 'auto'),
  ('fingolimod', '핀골리모드', array['핀골리모드염산염']::text[], 'auto/review'),
  ('flecainide', '초산플레카이니드', array['플레카이니드아세트산염']::text[], 'auto'),
  ('fluconazole', '플루코나졸', '{}'::text[], 'auto'),
  ('fluoxetine', '플루옥세틴', array['염산플루옥세틴','플루옥세틴염산염']::text[], 'auto'),
  ('flurbiprofen', '플루르비프로펜', '{}'::text[], 'auto'),
  ('fluticasone', '플루티카손', '{}'::text[], 'manual'),
  ('formoterol', '포르모테롤', array['포르모테롤푸마르산염수화물']::text[], 'auto/review'),
  ('fosaprepitant dimeglumine', '포스아프레피탄트 디메글루민염', '{}'::text[], 'auto/review'),
  ('foscarnet trisodium hexahydrate', '포스카네트', array['포스카네트나트륨수화물']::text[], 'auto+manual'),
  ('fosphenytoin', '포스페니토인', array['포스페니토인나트륨']::text[], 'auto'),
  ('frovatriptan', '프로바트립탄', array['프로바트립탄숙신산염일수화물']::text[], 'auto'),
  ('furosemide', '푸로세미드', '{}'::text[], 'auto'),
  ('fursultiamine', '푸르설티아민', '{}'::text[], 'manual'),
  ('gemifloxacin', '메탄설폰산제미플록사신', array['제미플록사신메탄설폰산염']::text[], 'auto'),
  ('gemigliptin', '제미글립틴', '{}'::text[], 'manual'),
  ('gentamicin', '겐타마이신', array['겐타마이신황산염']::text[], 'auto/review'),
  ('gestodene', '게스토덴', '{}'::text[], 'manual'),
  ('gilteritinib', '길테리티닙', array['길테리티닙푸마르산염']::text[], 'auto/review'),
  ('gimeracil', '기메라실', '{}'::text[], 'manual'),
  ('glecaprevir', '글레카프레비르', '{}'::text[], 'manual'),
  ('glibenclamide', '글리벤클라미드', '{}'::text[], 'auto/review'),
  ('gliclazide', '글리클라지드', '{}'::text[], 'manual'),
  ('glimepiride', '글리메피리드', '{}'::text[], 'manual'),
  ('glycine', '글리신', '{}'::text[], 'manual'),
  ('granisetron', '그라니세트론', array['그라니세트론염산염']::text[], 'auto'),
  ('guaifenesin', '구아이페네신', '{}'::text[], 'manual'),
  ('haloperidol', '할로페리돌', '{}'::text[], 'auto'),
  ('haloperidol decanoate', '할로페리돌', array['할로페리돌데카노에이트']::text[], 'auto+manual'),
  ('hemocoagulase', '헤모코아귤라제', '{}'::text[], 'auto'),
  ('hydroxychloroquine', '히드록시클로로퀸', array['히드록시클로로퀸황산염']::text[], 'auto'),
  ('hydroxyzine', '히드록시진', array['히드록시진염산염']::text[], 'auto'),
  ('ibrutinib', '이브루티닙', '{}'::text[], 'auto/review'),
  ('ibuprofen', '이부프로펜', array['새콤한오렌지맛']::text[], 'auto'),
  ('ibuprofen arginine', '이부프로펜아르기닌', '{}'::text[], 'auto'),
  ('ibuprofen lysine', '이부프로펜리신', '{}'::text[], 'auto/review'),
  ('ilaprazole', '일라프라졸', '{}'::text[], 'auto/review'),
  ('imipenem', '이미페넴', '{}'::text[], 'manual'),
  ('indomethacin', '인도메타신', '{}'::text[], 'auto/review'),
  ('iobitridol', '이오비트리돌', '{}'::text[], 'auto'),
  ('iodixanol', '요오딕사놀', '{}'::text[], 'auto'),
  ('iohexol', '이오헥솔', '{}'::text[], 'auto'),
  ('iomeprol', '이오메프롤', '{}'::text[], 'auto'),
  ('iopamidol', '이오파미돌', '{}'::text[], 'auto'),
  ('iopromide', '이오프로마이드', '{}'::text[], 'auto'),
  ('ioversol', '이오버솔', '{}'::text[], 'auto'),
  ('irbesartan', '이르베사르탄', '{}'::text[], 'manual'),
  ('irinotecan', '이리노테칸', array['이리노테칸염산염']::text[], 'auto'),
  ('isavuconazonium', '이사부코나조늄', array['이사부코나조늄황산염']::text[], 'auto'),
  ('isoniazid', '이소니아지드', '{}'::text[], 'manual'),
  ('isoproterenol', '이소프로테레놀', '{}'::text[], 'manual'),
  ('isosorbide dinitrate', '묽은이소소르비드이', array['묽은이소소르비드이질산염','이소소르비드이질산염지속과립','이소소르비드질산염']::text[], 'auto'),
  ('isosorbide mononitrate', '묽은이소소르비드일', array['묽은이소소르비드일질산염','이소소르비드일진산염','이소소르비드일질산염']::text[], 'auto'),
  ('isotretinoin', '이소트레티노인', '{}'::text[], 'auto'),
  ('itraconazole', '이트라코나졸고체분산체', array['이트라코나졸']::text[], 'auto'),
  ('ivabradine', '이바브라딘', array['이바브라딘염산염']::text[], 'auto'),
  ('ixazomib', '익사조밉시트레이트', '{}'::text[], 'auto'),
  ('ketoprofen', '케토프로펜', '{}'::text[], 'manual'),
  ('ketorolac tromethamine', '케토롤락트로메타민염', array['케토롤락트로메타민']::text[], 'auto'),
  ('l-lysine', '라이신', '{}'::text[], 'manual'),
  ('lamivudine', '라미부딘', '{}'::text[], 'auto'),
  ('lansoprazole', '란소프라졸과립', array['란소프라졸']::text[], 'auto'),
  ('ledipasvir', '레디파스비르', '{}'::text[], 'manual'),
  ('lercanidipine', '레르카니디핀', array['레르카니디핀염산염']::text[], 'auto'),
  ('letermovir', '레테르모비르', '{}'::text[], 'auto'),
  ('levodopa', '레보도파', '{}'::text[], 'manual'),
  ('levofloxacin', '레보플록사신', array['레보플록사신수화물']::text[], 'auto'),
  ('levomepromazine', '레보메프로마진', array['레보메프로마진말레산염','말레인산레보메프로마진']::text[], 'auto'),
  ('levonorgestrel', '레보노르게스트렐', '{}'::text[], 'manual'),
  ('linagliptin', '리나글립틴', '{}'::text[], 'manual'),
  ('linezolid', '리네졸리드', '{}'::text[], 'auto'),
  ('lithium', '탄산리튬', '{}'::text[], 'auto/review'),
  ('lobeglitazone', '로베글리타존', '{}'::text[], 'manual'),
  ('lorlatinib', '롤라티닙', '{}'::text[], 'auto'),
  ('losartan', '로사르탄', '{}'::text[], 'manual'),
  ('loxoprofen', '록소프로펜', array['록소프로펜나트륨','록소프로펜나트륨수화물']::text[], 'auto'),
  ('lurasidone', '루라시돈', array['루라시돈염산염']::text[], 'auto'),
  ('lysozyme', '리소짐', '{}'::text[], 'manual'),
  ('magnesium hydroxide', '수산화마그네슘', '{}'::text[], 'manual'),
  ('mefloquine', '메플로퀸', array['메플로퀸염산염']::text[], 'auto/review'),
  ('meloxicam', '멜록시캄', array['멜로시캄']::text[], 'auto'),
  ('mequitazine', '메퀴타진', '{}'::text[], 'auto'),
  ('mercaptopurine', '메르캅토푸린', array['메르캅토푸린수화물']::text[], 'auto/review'),
  ('meropenem', '메로페넴', array['메로페넴건조탄산나트륨','메로페넴삼수화물','메로페넴수화물']::text[], 'auto'),
  ('metformin', '메트포르민', array['메트포르민염산염','염산메트포르민']::text[], 'auto'),
  ('methotrexate', '메토트렉세이트', '{}'::text[], 'auto'),
  ('methylephedrine', '메틸에페드린', '{}'::text[], 'manual'),
  ('methylergometrine', '메틸에르고메트린', array['메틸에르고메트린말레산염']::text[], 'auto/review'),
  ('methylergonovine', '메틸에르고노빈', array['메틸에르고메트린말레산염']::text[], 'auto+manual'),
  ('methylphenidate', '메틸페니데이트', array['메틸페니데이트염산염']::text[], 'auto'),
  ('metoclopramide', '메토클로프라미드', array['메토클로프라미드염산염','메토클로프라미드염산염수화물']::text[], 'auto'),
  ('metronidazole', '메트로니다졸', array['메트로니다졸제제']::text[], 'auto'),
  ('micronized dolutegravir', '돌루테그라비르', '{}'::text[], 'manual'),
  ('micronized riociguat', '리오시구앗', '{}'::text[], 'auto'),
  ('midostaurin', '미도스타우린', '{}'::text[], 'auto/review'),
  ('minocycline', '미노사이클린', array['미노사이클린염산염']::text[], 'auto'),
  ('mirodenafil', '미로데나필', array['미로데나필염산염']::text[], 'auto'),
  ('mirtazapine', '미르타자핀', array['제피미르타자핀']::text[], 'auto'),
  ('mitotane', '미토테인', '{}'::text[], 'auto/review'),
  ('mizolastine', '미졸라스틴', '{}'::text[], 'auto/review'),
  ('modafinil', '모다피닐', '{}'::text[], 'auto'),
  ('molsidomin', '몰시도민', '{}'::text[], 'auto'),
  ('morphine', '모르핀', array['모르핀염산염수화물','모르핀황산염수화물','바이알','황산모르핀']::text[], 'auto'),
  ('moxifloxacin', '목시플록사신', array['목시플록사신염산염','병']::text[], 'auto'),
  ('nabumetone', '나부메톤', '{}'::text[], 'auto'),
  ('nafcillin', '나프실린', array['나프실린나트륨']::text[], 'auto/review'),
  ('naltrexone', '날트렉손', '{}'::text[], 'manual'),
  ('nanoliposomal irinotecan', '이리노테칸', array['나노리포좀이리노테칸']::text[], 'auto+manual'),
  ('naproxen', '나프록센', array['나프록센나트륨']::text[], 'auto'),
  ('naratriptan', '나라트립탄', array['나라트립탄염산염']::text[], 'auto'),
  ('natalizumab', '나탈리주맙', '{}'::text[], 'auto/review'),
  ('nebivolol', '네비볼롤', '{}'::text[], 'manual'),
  ('neratinib', '네라티닙', array['네라티닙말레산염']::text[], 'auto/review'),
  ('netilmicin', '네틸마이신', array['네틸마이신황산염']::text[], 'auto'),
  ('netupitant', '네투피탄트', '{}'::text[], 'manual'),
  ('nicorandil', '니코란딜', '{}'::text[], 'auto'),
  ('nifedipine', '니페디핀', '{}'::text[], 'auto'),
  ('nilotinib', '닐로티닙', array['닐로티닙염산염일수화물']::text[], 'auto'),
  ('nimesulide', '니메술리드', '{}'::text[], 'auto/review'),
  ('nirmatrelvir', '니르마트렐비르', '{}'::text[], 'manual'),
  ('norepinephrine', '노르에피네프린', array['노르에피네프린타르타르산염수화물','주석산수소노르에피네프린']::text[], 'auto'),
  ('nortriptyline', '염산노르트립틸린', '{}'::text[], 'auto'),
  ('noscapine', '노스카핀', '{}'::text[], 'manual'),
  ('octreotide', '옥트레오티드', array['옥트레오티드아세테이트','옥트레오티드아세트산염']::text[], 'auto'),
  ('olanzapine', '올란자핀', array['미세올란자핀']::text[], 'auto'),
  ('olmesartan medoxomil', '올메사르탄', '{}'::text[], 'manual'),
  ('omega-3-acid ethyl ester 90', '오메가-3산에틸에스테르', '{}'::text[], 'manual'),
  ('omega-3-acid ethyl esters 90', '오메가-3산에틸에스테르', '{}'::text[], 'manual'),
  ('omega-3-acid ethyl esters90', '오메가-3산에틸에스테르', '{}'::text[], 'manual'),
  ('omeprazole', '오메프라졸', array['오메프라졸장용성과립']::text[], 'auto'),
  ('omidenepag isopropyl', '오미데네팍이소프로필', '{}'::text[], 'auto'),
  ('ondansetron', '온단세트론', array['바이알','온단세트론염산염','온단세트론염산염수화물']::text[], 'auto'),
  ('oteracil', '오테라실', '{}'::text[], 'manual'),
  ('oxatomide', '옥사토마이드', '{}'::text[], 'auto/review'),
  ('oxcarbazepine', '옥스카르바제핀', '{}'::text[], 'auto'),
  ('oxymetazoline', '옥시메타졸린', array['옥시메타졸린염산염']::text[], 'auto'),
  ('ozanimod', '오자니모드', array['오자니모드염산염']::text[], 'auto/review'),
  ('palbociclib', '팔보시클립', '{}'::text[], 'auto'),
  ('paliperidone', '팔리페리돈팔미테이트', '{}'::text[], 'auto'),
  ('palonosetron', '팔로노세트론', '{}'::text[], 'manual'),
  ('pantoprazole', '판토프라졸나트륨세스키히드레이트', '{}'::text[], 'auto'),
  ('pantoprazole hemimagnesium', '판토프라졸헤미', array['판토프라졸헤미마그네슘수화물']::text[], 'auto/review'),
  ('paricalcitol', '파리칼시톨', '{}'::text[], 'auto'),
  ('paroxetine', '파록세틴', array['무수염산파록세틴','파록세틴염산염반수화물','파록세틴염산염수화물']::text[], 'auto'),
  ('pentamidine isethionate', '펜타미딘', '{}'::text[], 'manual'),
  ('pentoxifylline', '펜톡시필린', '{}'::text[], 'auto'),
  ('perphenazine', '페르페나진', array['페르페나진염산염']::text[], 'auto/review'),
  ('pethidine', '페티딘', '{}'::text[], 'manual'),
  ('phendimetrazine', '펜디메트라진', array['펜디메트라진타르타르산염']::text[], 'auto'),
  ('phenobarbital', '페노바르비탈', array['앰플','페노바르비탈나트륨']::text[], 'auto'),
  ('phentermine', '펜터민', array['펜터민염산염']::text[], 'auto'),
  ('phentermine hcl', '펜터민', array['펜터민염산염']::text[], 'auto/review'),
  ('phenylephrine', '페닐에프린', '{}'::text[], 'manual'),
  ('phenytoin', '페니토인', array['페니토인나트륨']::text[], 'auto/review'),
  ('pibrentasvir', '피브렌타스비르', '{}'::text[], 'manual'),
  ('pilsicainide', '필시카이니드', array['필시카이니드염산염']::text[], 'auto'),
  ('pimozide', '피모지드', '{}'::text[], 'manual'),
  ('pioglitazone', '피오글리타존', '{}'::text[], 'manual'),
  ('pirfenidone', '피르페니돈', '{}'::text[], 'auto'),
  ('piroxicam', '피록시캄', array['피록시캄칼륨']::text[], 'auto'),
  ('piroxicam β-cyclodextrin', '피록시캄베타사이클로덱스트린', '{}'::text[], 'auto/review'),
  ('pitavastatin', '피타바스타틴', array['피타바스타틴칼슘','피타바스타틴칼슘수화물']::text[], 'auto'),
  ('ponatinib', '포나티닙', array['포나티닙염산염']::text[], 'auto'),
  ('posaconazole', '포사코나졸', '{}'::text[], 'manual'),
  ('potassium', '포타시움크로라이드주', array['구연산칼륨','염화칼륨']::text[], 'auto'),
  ('pramipexole dihydrochloride', '프라미펙솔', array['프라미펙솔염산염일수화물']::text[], 'auto'),
  ('praziquantel', '프라지콴텔', '{}'::text[], 'auto/review'),
  ('primidone', '프리미돈', '{}'::text[], 'manual'),
  ('procaterol', '프로카테롤', array['프로카테롤염산염수화물']::text[], 'auto'),
  ('propafenone', '프로파페논', array['프로파페논염산염']::text[], 'auto'),
  ('prucalopride', '프루칼로프라이드', array['프루칼로프라이드숙신산염']::text[], 'auto'),
  ('pseudoephedrine', '슈도에페드린', array['수도에페드린염산염','슈도에페드린염산염']::text[], 'auto'),
  ('pyrazinamide', '피라진아미드', '{}'::text[], 'manual'),
  ('quetiapine', '쿠에티아핀', array['쿠에티아핀푸마르산염']::text[], 'auto'),
  ('rabeprazole', '라베프라졸', array['라베프라졸나트륨']::text[], 'auto'),
  ('radotinib', '라도티닙', array['라도티닙염산염']::text[], 'auto'),
  ('ranolazine', '라놀라진', '{}'::text[], 'auto'),
  ('rasagiline', '라사길린', array['라사길린메실산염']::text[], 'auto'),
  ('recombinant human tissue-type plasminogen activator', '알-티피에이', '{}'::text[], 'auto'),
  ('revaprazan', '레바프라잔', array['레바프라잔염산염']::text[], 'auto/review'),
  ('ribociclib', '리보시클립', array['리보시클립숙신산염']::text[], 'auto/review'),
  ('riboflavin', '리보플라빈', '{}'::text[], 'manual'),
  ('rifabutin', '리파부틴', '{}'::text[], 'auto/review'),
  ('rifampicin', '리팜피신', '{}'::text[], 'auto'),
  ('rilpivirine', '릴피비린', array['릴피비린염산염']::text[], 'auto/review'),
  ('rilpivirine micronized', '릴피비린', '{}'::text[], 'auto+manual'),
  ('risperidone', '리스페리돈', '{}'::text[], 'auto'),
  ('ritonavir', '리토나비르', '{}'::text[], 'auto/review'),
  ('rivaroxaban', '리바록사반', '{}'::text[], 'auto'),
  ('rosuvastatin', '로수바스타틴', array['로수바스타틴칼슘']::text[], 'auto'),
  ('roxithromycin', '록시트로마이신', '{}'::text[], 'auto'),
  ('s-pantoprazole', '에스-판토프라졸나트륨 ', array['에스-판토프라졸나트륨 삼수화물','에스-판토프라졸나트륨삼수화물']::text[], 'auto'),
  ('safinamide', '사피나미드', array['사피나미드메실산염']::text[], 'auto/review'),
  ('salbutamol', '살부타몰', array['살부타몰황산염']::text[], 'auto'),
  ('salmeterol xinafoate', '살메테롤', '{}'::text[], 'manual'),
  ('saxagliptin', '삭사글립틴', '{}'::text[], 'manual'),
  ('selegiline', '셀레길린', array['셀레길린염산염']::text[], 'auto/review'),
  ('sertraline', '설트랄린', array['설트랄린염산염','염산설트랄린']::text[], 'auto'),
  ('sildenafil', '실데나필', array['실데나필시트르산염']::text[], 'auto'),
  ('silodosin', '실로도신', '{}'::text[], 'auto'),
  ('simvastatin', '심바스타틴', '{}'::text[], 'auto'),
  ('sirolimus', '시롤리무스', '{}'::text[], 'auto'),
  ('sitagliptin', '시타글립틴', '{}'::text[], 'manual'),
  ('sodium alendronate', '알렌드로네이트', '{}'::text[], 'manual'),
  ('sodium bicarbonate', '탄산수소나트륨', '{}'::text[], 'manual'),
  ('sodium nitroprusside', '니트로푸루시드', array['니트로푸루시드나트륨']::text[], 'auto/review'),
  ('sodium valproate', '발프로산', array['발프로산나트륨','발프론산나트륨']::text[], 'auto'),
  ('sofosbuvir', '소포스부비르', '{}'::text[], 'manual'),
  ('sotalol', '소타롤', array['소타롤염산염']::text[], 'auto/review'),
  ('spiramycin', '스피라마이신', '{}'::text[], 'manual'),
  ('spironolactone', '스피로노락톤', '{}'::text[], 'auto'),
  ('sulfamethoxazole', '설파메톡사졸', '{}'::text[], 'manual'),
  ('sumatriptan', '수마트립탄', array['수마트립탄숙신산염','호박산수마트립탄']::text[], 'auto'),
  ('tacrolimus', '타크로리무스', array['타크로리무스수화물']::text[], 'auto'),
  ('tadalafil', '타다라필', '{}'::text[], 'auto'),
  ('tafluprost', '타플루프로스트', '{}'::text[], 'auto'),
  ('tamoxifen', '타목시펜', array['타목시펜시트르산염']::text[], 'auto'),
  ('tamsulosin', '탐스로신', array['염산탐스로신','탐스로신염산염']::text[], 'auto'),
  ('tapentadol', '타펜타돌', array['타펜타돌염산염']::text[], 'auto'),
  ('tegafur', '테가푸르', '{}'::text[], 'manual'),
  ('tegoprazan', '테고프라잔', '{}'::text[], 'auto'),
  ('telmisartan', '텔미사르탄', '{}'::text[], 'manual'),
  ('teneligliptin', '테네리글립틴', '{}'::text[], 'manual'),
  ('tenofovir alafenamide', '테노포비르알라페나미드', array['테노포비르알라페나미드숙신산염','테노포비르알라페나미드시트르산염']::text[], 'auto'),
  ('tenofovir alafenamide hemifumarate', '테노포비르알라페나미드헤미', array['테노포비르알라페나미드헤미푸마르산염']::text[], 'auto/review'),
  ('tenofovir alafenamide hemimalate', '테노포비르알라페나미드헤미', array['테노포비르알라페나미드헤미말산염']::text[], 'auto'),
  ('tenofovir alafenamide hemitartrate', '테노포비르알라페나미드헤미', array['테노포비르알라페나미드헤미타르타르산염']::text[], 'auto/review'),
  ('tenofovir disoproxil', '테노포비르디소프록실', array['테노포비르디소프록실인산염','테노포비르디소프록실푸마르산염']::text[], 'auto'),
  ('tenofovir disoproxil asparate', '테노포비르디소프록실아스파르트산염', '{}'::text[], 'auto/review'),
  ('tenofovir disoproxil hemiedisylate', '테노포비르디소프록실헤미에디실산염', '{}'::text[], 'auto'),
  ('tenofovir disoproxil orotate', '테노포비르디소프록실오로트산염', '{}'::text[], 'auto/review'),
  ('tetracycline', '염산테트라싸이클린', '{}'::text[], 'auto/review'),
  ('thiamine', '티아민', '{}'::text[], 'manual'),
  ('thrombin', '트롬빈', '{}'::text[], 'auto'),
  ('ticagrelor', '티카그렐러', '{}'::text[], 'auto'),
  ('tigecycline', '타이제사이클린', '{}'::text[], 'auto/review'),
  ('timolol', '티몰롤', '{}'::text[], 'manual'),
  ('tizanidine', '티자니딘', array['염산티자니딘','티자니딘염산염']::text[], 'auto'),
  ('tofacitinib', '토파시티닙', array['토파시티닙시트르산염']::text[], 'auto'),
  ('tofacitinib aspartate', '토파시티닙아스파르트산염', '{}'::text[], 'auto'),
  ('tolvaptan', '톨밥탄', '{}'::text[], 'auto'),
  ('tolvaptan sd powder', '톨밥탄분무건조분말', '{}'::text[], 'auto'),
  ('topiramate', '토피라메이트', '{}'::text[], 'auto'),
  ('tramadol', '트라마돌', array['트라마돌염산염']::text[], 'auto'),
  ('tranexamic acid', '트라넥삼산', '{}'::text[], 'auto'),
  ('trastuzumab emtansine', '트라스투주맙엠탄신', '{}'::text[], 'auto'),
  ('trazodone', '트라조돈', array['트라조돈염산염']::text[], 'auto'),
  ('tretinoin', '트레티노인', '{}'::text[], 'auto/review'),
  ('triazolam', '트리아졸람', '{}'::text[], 'auto'),
  ('trimethoprim', '트리메토프림', '{}'::text[], 'manual'),
  ('trimetoquinol', '트리메토퀴놀', '{}'::text[], 'manual'),
  ('triprolidine', '트리프롤리딘', '{}'::text[], 'manual'),
  ('tulobuterol', '툴로부테롤', '{}'::text[], 'auto'),
  ('udenafil', '유데나필', '{}'::text[], 'auto'),
  ('valbenazine', '발베나진이', array['발베나진이토실산염']::text[], 'auto/review'),
  ('valproate', '발프로산', array['발프로산마그네슘']::text[], 'auto'),
  ('valsartan', '발사르탄', '{}'::text[], 'manual'),
  ('vandetanib', '반데타닙', '{}'::text[], 'auto'),
  ('vardenafil', '바데나필', array['바데나필염산염']::text[], 'auto'),
  ('vedolizumab', '베돌리주맙', '{}'::text[], 'auto'),
  ('velpatasvir', '벨파타스비르', '{}'::text[], 'manual'),
  ('venetoclax', '베네토클락스', '{}'::text[], 'auto'),
  ('venlafaxine', '벤라팍신', array['벤라팍신염산염']::text[], 'auto'),
  ('verapamil', '베라파밀', array['베라파밀염산염']::text[], 'auto'),
  ('vildagliptin', '빌다글립틴', '{}'::text[], 'manual'),
  ('vincristine', '빈크리스틴', array['빈크리스틴황산염']::text[], 'auto/review'),
  ('voriconazole', '보리코나졸', array['주사용']::text[], 'auto'),
  ('vortioxetine', '보티옥세틴', array['보티옥세틴브롬화수소산염']::text[], 'auto'),
  ('voxilaprevir', '복실라프레비르', '{}'::text[], 'manual'),
  ('xylometazoline', '자일로메타졸린', array['자일로메타졸린염산염']::text[], 'auto'),
  ('zaltoprofen', '잘토프로펜', '{}'::text[], 'auto'),
  ('zanubrutinib', '자누브루티닙', '{}'::text[], 'auto/review'),
  ('zidovudine', '지도부딘', '{}'::text[], 'manual'),
  ('zinc histidine', '히스티딘아연', array['히스티딘아연이수화물']::text[], 'auto/review'),
  ('ziprasidone', '염산지프라시돈', array['염산지프라시돈일수화물']::text[], 'auto'),
  ('zolmitriptan', '졸미트립탄', '{}'::text[], 'auto/review');

-- §1 미리보기: 추가될 것(이미 있는 code·name_ko 제외)
select n.code, n.name_ko, n.aliases, n.src from _new_subst n
where not exists (select 1 from interaction.substance s where s.code = n.code)
  and not exists (select 1 from interaction.substance s where s.name_ko = n.name_ko)
order by n.src, n.code;

-- §2 적용
insert into interaction.substance (code, kind, name_ko, name_en, aliases)
select n.code, (select s0.kind from interaction.substance s0 where s0.code = 'aspirin'), n.name_ko, n.code, n.aliases
from _new_subst n
where not exists (select 1 from interaction.substance s where s.code = n.code)
  and not exists (select 1 from interaction.substance s where s.name_ko = n.name_ko)
  and n.src not like '%/review';   -- 검수 플래그(근거 제품 1개뿐)는 넣지 않는다 — seed/substance_expand_candidates.csv 참고

-- §3 확인
select count(*) as total_substances from interaction.substance;
select code, name_ko, aliases from interaction.substance where code in ('sertraline','omeprazole','amlodipine','losartan','acetaminophen','sitagliptin') order by code;
